trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      PYTHON_VERSION: '3.6'
    Python37:
      PYTHON_VERSION: '3.7'
  maxParallel: 2

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: |
    python3 -m pip install --upgrade pip setuptools wheel


- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    pip install unittest-xml-reporting
  displayName: 'unit test'


- script: |
    python3 manage.py test app
  displayName: 'Run tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
