# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

steps:
- script: ls
  displayName: 'checking working directory'

- script: |
    python3 -m pip install --upgrade pip setuptools wheel
- script: |
    pip install pipenv
  displayName: 'Install pipenv'

- script: |
    pipenv shell
  displayName: 'pipenv shell'


- script: |
    pipenv install
    pip install unittest-xml-reporting
  displayName: 'pipenv install'

- script: |
    pipenv install unittest-xml-reporting
  displayName: 'unit test'


- script: |
    python manage.py test app
  displayName: 'Run tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
